### ISSUE TITLE
read proc using (now removed) juttle argument

### ISSUE THREAD

**Issue by mstemm** [juttle/juttle-graphite-adapter#21]
After updating the graphite adapter to juttle 0.3.0, I noticed that the graphite adapter was using the (now removed) juttle argument to the read proc.

It's eval()ing code which refers to juttle, which is not avalable in the adapter's scope:

```
if (name) {
                    /* jshint evil: true */
                    this.filter = eval(source);
                }
```

source contains ``(function(pt) { return juttle.ops.eql(juttle.ops.pget(pt, "name"), "metricaf0c1a") })``

In order to release outrigger we need to fix this or drop support for the graphite adapter temporarily.

**Comment by rlgomes** [comment]
I think this is a bug as that code wasn't necessary. The whole point of only accept filter expressions containing the name was so we could pass it to graphite as we do below:

https://github.com/juttle/juttle-graphite-adapter/blob/master/lib/read.js#L86

I'll put together a PR that shows this and removes that code completely and we can merge in the morning.
